---
# This playbook will install puppet

- name: install perl
  apt: pkg={{item}} install_recommends=no state=installed
  with_items:
    - perl
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Download puppet package
  get_url:
    url="{{download_url}}"
    dest="/{{package_name}}"

- name: Install puppet release repository debian package
  apt: deb="/{{package_name}}"
  sudo: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install puppet
  apt: pkg={{item}} install_recommends=no state=latest update_cache=yes
  with_items:
    - puppet
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: create morpheus entrypoint
  template: src=morpheus-entrypoint.sh.j2 dest=/entrypoint.sh mode=0777
