---
- hosts: all
  vars:
    download_url: http://archive.apache.org/dist/activemq/5.13.4/apache-activemq-5.13.4-bin.tar.gz
    package_name: apache-activemq-5.13.4
  become: yes
  become_method: sudo
  gather_facts: yes

  roles:
    - activemq-5_11
