---
- name: Test ansible facts with Morpheus run.
  hosts: all
  gather_facts: yes
  tasks:    
    - debug:
        msg: the tenant is {{ morpheus['account'] }}
        msg: Output of task 1 is {{ morpheus['results']['taskone'] }}