---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - yum: "name={{ item }} state=latest"
      with_items:
        - git
        - wget
        - curl
        - vim
