---
- name: This sets up an mysql master server
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Install mysql packages 
    yum:
      name: mariadb-server
      state: present
  - name: ensure mysql is running
    service:
      name: mariadb 
      state: started