---
- name: This sets up a service by accepting values from Option Types.
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Install package
    yum:
      name: httpd
      state: present
  - name: ensure apache2 is running
    service:
      name: httpd 
      state: started