---
- name: This sets up an mysql master server
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Create a User
    mysql_user:
      name: 'anish'
      password: 12345
      priv: '*.*:ALL'
      host: localhost
      state: present
      delegate_to: "{{ lookup('env','MARIADB_IP') }}"