---
- name: This sets up an mysql master server
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Creates directory
      file:
        path: /home/"{{ morpheus['customOptions']['pname'] }}"
        state: directory