---
- hosts: all
  gather_facts: true
  plugin: morpheus_inventory
  groups:
    - name: morphtest
      searchtype: label
      searchstring: ubuntu
  morpheus_url: https://10.0.255.21/
  morpheus_api_key: 5e44a919-a023-469a-b9d7-f077e8dee089
