---
- name: Read contents of a file
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  #- name: slurp file
  #  slurp:
  #    src: /home/ips
  #  register: remote_file
  
  #- name: Read
  #  debug: 
  #    msg: "{{ remote_file['content'] | b64decode }}"
  - name: slurp file
    command: cat /tmp/ips
    register: remote_file

  - name: readloop
    debug: 
      msg: "{{ item }}"
    loop: "{{ remote_file.stdout_lines }}"  