---
- name: Refresh clouds.
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Refresh the clouds
    uri:
      url: https://applianceurl/api/zones/{{ item }}
      HEADER_Content-Type: "application/json"
      HEADER_Authorization: "Bearer xxx"
      method: PUT
      body: "{{ lookup('file','update_cloud.json') }}"
      body_format: json
    with_items:
        - 2
        - 32
