galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible](https://www.ansible.com) role to install [Windows - IIS](https://www.iis.net/)

  license: license (MIT)

  min_ansible_version: 2.5

  platforms:
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - windows
    - webserver

dependencies: []
collections:
  - ansible.windows
  - community.windows
