---
- name: reboot | Regathering Facts To Determine If Reboot Is Required
  setup:

- name: reboot | Rebooting Server
  win_reboot:
    reboot_timeout: 3600
    shutdown_timeout: 3600
  when: ansible_reboot_pending
