---
# This playbook will install jboss

- name: install perl openjdk-7-jdk pwgen
  apt: pkg={{item}} install_recommends=no state=installed
  with_items:
    - perl
    - openjdk-7-jdk
    - pwgen
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: download jboss package
  get_url: url={{download_url}} dest=/{{package_name}} validate_certs=no

- name: install jboss
  shell: apt-get update && cd / && tar zxf /{{package_name}} && rm jboss-as-7.1.1.Final.tar.gz && ln -s jboss-as-7.1.1.Final jboss
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: jboss bind address configuration
  shell: sed -i -r 's/jboss.bind.address.management:127.0.0.1/jboss.bind.address.management:0.0.0.0/' /jboss-as-7.1.1.Final/standalone/configuration/standalone.xml

- name: create jboss log directory
  file: path=/jboss-as-7.1.1.Final/standalone/log state=directory recurse=yes mode=0777

- name: create morpheus entrypoint
  template: src=morpheus-entrypoint.sh.j2 dest=/entrypoint.sh mode=0777

- name: copy jboss admin pass script
  template: src=set_jboss_admin_pass.sh.j2 dest=/set_jboss_admin_pass.sh mode=0777

- name: copy config
  shell: mkdir -p /tmp/config && cp -r /jboss/standalone/configuration/* /tmp/config/

- name: set environment var
  lineinfile: dest=/etc/environment state=present regexp='^JBOSS_PASS' line='JBOSS_PASS=**Random**'

- name: add jboss upstart
  template: src=jboss.conf.j2 dest=/etc/init/jboss.conf mode=0644

- name: add upstart override
  template: src=jboss.override.j2 dest=/etc/init/jboss.override mode=0644
