---
# This playbook will install elasticsearch

- name: install perl
  apt: pkg={{item}} install_recommends=no state=installed
  with_items:
    - perl
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Download elasticsearch package
  get_url:
    url="{{download_url}}"
    dest="/{{package_name}}"

- name: Install elasticsearch
  apt: deb="/{{package_name}}"
  sudo: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: create morpheus entrypoint
  template: src=morpheus-entrypoint.sh.j2 dest=/entrypoint.sh mode=0777
  
- name: copy debian package configuration file
  template: src=elasticsearch.j2 dest=/etc/default/elasticsearch mode=0644
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: create morpheus entrypoint
  template: src=morpheus-entrypoint.sh.j2 dest=/entrypoint.sh mode=0777
